### ISSUE TITLE
Mail-naming / -labeling not working properly with commas

### ISSUE THREAD

**Issue by pdiegmann** [eleith/emailjs#120]
While
```
var message = { 
    ... 
        from: "\"FirstName Last Name\" <address>"
    ... 
}
```
or even
```
from: "FirstName Last Name <address>"
```
work like a charm, anything containing a comma is failing to be sent, as emailjs interprets the comma as always being a delimiter of different addresses. I tried all of the following:
```
from: "FirstName, Last Name <address>"
```
```
from: "\"FirstName, Last Name\" <address>"
```
```
from: "FirstName\\, Last Name <address>"
```
```
from: "\"FirstName\\, Last Name\" <address>"
```
But I always got the message:
```
code: 2,
smtp: '553 5.5.4 <=?UTF-8?Q?LastName>... Domain name required for sender address =?UTF-8?Q? LastName\n' }
```

Is there any way to encode a comma? As many users might want to use a label like Last Name, First Name.

Thank you for your support!

**Comment by eleith** [comment]
it's a pretty tricky issue since this field allows for commas to indicate how to separate email addresses from each other.

i've made some updates to the library and there is now a way to send commas. you will have to quote the name field. i also recommend using arrays if you are passing in more than one field and you want to use commas in the name field. so for example

```from: \"firstName, lastName\" <address@>```
