### ISSUE TITLE
Custom Headers

### ISSUE THREAD

**Issue by aconite33** [eleith/emailjs#147]
Is it possible to create custom headers in your message?

**Comment by eleith** [comment]
yes.

you can send it custom headers when calling `email.server.send` as documented here: https://github.com/eleith/emailjs#message


you can inspect the code for what happens when you send custom headers: https://github.com/eleith/emailjs/blob/b4b8294bf7cd5572d5bb58199c1e429c024c6866/smtp/message.js#L58
