### ISSUE TITLE
UTF Encoding in From field

### ISSUE THREAD

**Issue by aconite33** [eleith/emailjs#152]
I'm having an issue where I'd like emailjs not to send UTF encoded From headers.
Right now I'm using Meteor with the emailjs wrapper and when I have a display name and a from address, the display name gets wrapped into UTF encoding.

Example:
server.send({
     from: emailJSON.displayFrom + ' ' + emailJSON.emailFrom,
     ...

Results in:
From: =?UTF-8?Q?DisplayFrom?= <sender@address.com>

However, if I just use the straight Email From address I do not get any UTF encoding.
server.send({
     from: emailJSON.emailFrom,
     ...

Result:
From: sender@address.com

**Comment by eleith** [comment]
this happens here: https://github.com/eleith/emailjs/blob/2c5006761b40a79b2405c3c2b2dfea3e5da664ca/smtp/message.js#L33

basically, anytime you send in an email address with a label (as opposed to only sending the email address alone), then it will format the label, so that it can encode it properly in the mimeheader.

why do you want to avoid the encoding? do you want to encode it with a different encoding? we could possibly support additional encodings...
