### ISSUE TITLE
Override Headers like Message-Id

### ISSUE THREAD

**Issue by cortezcristian** [eleith/emailjs#178]
Add the posibility to override the headers like "message-id"

```js
var Message = function(headers)
{
   this.attachments  = [];
   this.alternative  = null;
   var now = new Date();
   this.header       = {
      "message-id":"<" + now.getTime() + "." + (counter++) + "." + process.pid + "@" + os.hostname() +">",
      "date":moment().locale('en').format("ddd, DD MMM YYYY HH:mm:ss ZZ")
   };
   this.content      = "text/plain; charset=utf-8";

   for(var header in headers)
```

The documentation `README.md` says that:

```
// headers is an object ('from' and 'to' are required)
// returns a Message object

// you can actually pass more message headers than listed, the below are just the
// most common ones you would want to use
``` 

But message-id can't currently be overrided. In my debugging session `headers` params going into the Message function are only: {from, submit, to, attachment} dispite I send "message-id" too.

**Comment by eleith** [comment]
i'll debug a bit. but i would expect this line to do what you intended

https://github.com/eleith/emailjs/blob/master/smtp/message.js#L93

let me explore a bit to see if i confirm.

can you also post the code you are using to override `message-id` ?

**Comment by eleith** [comment]
i've added in a test (and it passes) showing how to override message-id. 

https://github.com/eleith/emailjs/blob/master/test/message.js#L64

in theory, this get's output on this line

https://github.com/eleith/emailjs/blob/master/smtp/message.js#L298

are you not seeing it there?

otherwise, it looks like it is possible. perhaps looking at how you were trying would help me see what might be different than what i expected?

**Comment by cortezcristian** [comment]
Sorry my bad, it works perfectly the only time i have the complete code in place i didn't see the "X-Google-Original-Message-ID". So it works as expected, thanks for adding the test cases, that helped me.
