### ISSUE TITLE
MessageAttachment Typescript Type

### ISSUE THREAD

**Issue by wyattjoh** [eleith/emailjs#254]
Your examples show the following:

```js
// ...
const message = {
        // ...
	attachment: [
		{ data: '<html>i <i>hope</i> this works!</html>', alternative: true }
	],
};

client.send(message);
// ...
```

Yet the typescript type for the `MessageAttachment` does not allow that, causing you to do the following in your tests:

https://github.com/eleith/emailjs/blob/0781d02cbf7de0d55b417d00ae7f5ab1283bf527/test/message.ts#L166-L169

It's amazing that this project exports typescript types, but it would be helpful to correct this type so that you don't have this complexity of having to type cast the attachment.

**Comment by zackschuster** [comment]
@wyattjoh thanks for your feedback! i'm glad the types are useful for you :)

i went over the `MessageAttachment` interface again and managed to fix this. that in turn revealed the `stream` property was improperly typed — it should've been `ReadStream`, not `Duplex` — so double-kudos for pointing this out!

as a bonus, i was also able to merge it with `AlternateMessageAttachment`, so that's one less thing to keep track of :) i think it's ok to ship that as `semver-patch` since, as you pointed out, the types were essentially unusable before.

you can review these changes from the following commit:
- smtp/message: fix attachment interface usability 19bda25f6702f2f37f88000144feff406f8022f8

@eleith would you like to ship this now or after #252 is done? are you ok with it being `semver-patch`?

**Comment by eleith** [comment]
let's do it after #252 if you think we can get this in this week?

**Comment by zackschuster** [comment]
yes, that's doable

**Comment by wyattjoh** [comment]
Thank you for the fast response!! 👏

**Comment by zackschuster** [comment]
@wyattjoh as of `3.2.0` you should be able to use the code without type errors. you can also drop the `typeRoots` workaround in `tsconfig.json`, if you had included that.
