### ISSUE TITLE
Receive emails using emailjs

### ISSUE THREAD

**Issue by somilmathur** [eleith/emailjs#273]
Hi this may be a somewhat dumb question but I'm just starting to learn about email clients and servers. Any help would be greatly appreciated. 

I am trying to make a nodejs application that connects to any mailbox (google, outlook etc) and receives them and shows them on a react frontend. I am not looking for any send mail functionality as of yet. Just to receive mails and display them.

Can I achieve this using emailjs? If yes, how? 

What is the best way to achieve this if not emailjs?

**Comment by zackschuster** [comment]
we don't support receiving emails — this library is only for sending them. for testing we use nodemailer's [`smtp-server`](https://github.com/nodemailer/smtp-server), which might suit your needs. 

however, since your use-case involves a pre-existing mail service, i would suggest looking at that service's existing API options. outlook, for instance, has a [fairly robust API](https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/mail-rest-operations) not just for retrieving messages but sending them as well.

hope that helps 😄

**Comment by eleith** [comment]
i recommend checking out https://github.com/roundcube/roundcubemail 

it's a solid PHP frontend for sending/receiving email that can give you pointers on some of the questions you raised.
