### ISSUE TITLE
{"code":2,"message":"bad response on command 'mail'","smtp":"503 5.5.1 EHLO/HELO first. hc4sm19538897pbc.29 - gsmtp\n","error":null}

### ISSUE THREAD

**Issue by dennisa** [eleith/emailjs#92]
when connecting to gmail's smtp server I get the following error.

any idea what might be wrong? here are my config settings:

   { username: 'xxxxxxx@gmail.com',
     password: 'xxxxxxxx',
     host: 'smtp.gmail.com',
     port: null,
     ssl: false,
     tls: true,
     timeout: 120000,
     domain: null } }

**Comment by RevealedFrom** [comment]
I have been using emailjs for many years without issue. Thanks! But in the past week, from an application that was working fine all these years, when trying to send a mail, to multiple addressees, all the Gmail (@gmail.com) addressees result in `SMTPError: bad response on command 'mail': Bye`. What can this be due to?

**Comment by RevealedFrom** [comment]
Besides the exception returned from the `send` method in `emailjs`, there was an NDR generated by AWS SES. There were a total 12 addressees in the To and BCC fields. Only the Gmail accounts were in the error message. 

![image](https://github.com/eleith/emailjs/assets/5305957/e9abb8ff-058e-4680-a1fc-24477a9b5920)

Oddly, when the total addressees were 3 or 4, all messages, including to Gmail ones, were delivered. I think the problem is in AWS SES. I switched to Axure Sendgrid and the same problematic scenario worked ok now.

**Comment by eleith** [comment]
thanks for the follow-up. email sending is tricky the more you send and the more people one email is being sent to.
